import { z } from 'zod'

/**
 * Zod schemas enforcing Hermes Agent's "HARDLINE" skill-authoring standards.
 * These are the same rules a maintainer enforces in review — the description
 * is truncated to 60 chars in the system-prompt skill index, so anything past
 * char 60 is silently cut and never routes.
 */

export const platformSchema = z.enum(['macos', 'linux', 'windows'])

export const skillFrontmatterSchema = z.object({
  name: z
    .string()
    .max(64)
    .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, 'name must be lowercase-hyphenated, no spaces'),
  description: z
    .string()
    .max(60)
    .refine(v => v.trim().endsWith('.'), 'description must be ONE sentence ending with a period (<=60 chars)'),
  version: z.string().regex(/^\d+\.\d+\.\d+$/, 'version must be semver (e.g. 0.1.0)'),
  author: z.string().min(1),
  platforms: z.array(platformSchema).optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
})

export const skillBodySchema = z.object({
  title: z.string().min(1),
  intro: z.string().optional(),
  whenToUse: z.array(z.string()).min(1),
  prerequisites: z.array(z.string()).optional(),
  howToRun: z.string().optional(),
  quickReference: z.array(z.string()).optional(),
  procedure: z.array(z.string()).min(1),
  pitfalls: z.array(z.string()).optional(),
  verification: z.string().optional(),
})

/**
 * Shape produced by the LLM and validated structurally. `module` is intentionally
 * excluded — functions cannot be generated by a model, so generated skills carry
 * documentation only (hand-authored skills may add a `module` via {@link defineSkill}).
 */
export const skillGenerationSchema = z.object({
  frontmatter: skillFrontmatterSchema,
  body: skillBodySchema,
})

export type SkillFrontmatterParsed = z.infer<typeof skillFrontmatterSchema>
export type SkillBodyParsed = z.infer<typeof skillBodySchema>
export type SkillGenerationParsed = z.infer<typeof skillGenerationSchema>
